name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build API
      run: dotnet build IdeventAPI --no-restore
    - name: Build Blazor Project
      run:  dotnet build IdeventAdminBlazorServer --no-restore
    - name: Test API
      run: dotnet test IdeventAPI --no-build --verbosity normal
    - name: Test Blazor Project
      run: dotnet test IdeventAdminBlazorServer --no-build --verbosity normal
